[project]
name = "wiktionary"
version = "0.1.0"
description = "Wiktionary parser and generator for Python."
readme = "README.md"
authors = [{ name = "mkpoli", email = "git@mkpo.li" }]
requires-python = ">=3.12"
dependencies = ["regex>=2024.11.6", "wikitext"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/jawikt", "src/wiktionary"]
exclude = ["tests"]

[tool.uv.sources]
wikitext = { workspace = true }
